// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv-FDkzio5qAQl_kkqD6XuCYL_GJm7mjg',
    appId: '1:531701629996:web:4e10653d8153f7e19d7d89',
    messagingSenderId: '531701629996',
    projectId: 'pentexe-3933d',
    authDomain: 'pentexe-3933d.firebaseapp.com',
    storageBucket: 'pentexe-3933d.appspot.com',
    measurementId: 'G-2T1R830PFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy3hi4nkETQdnGu2Mv6HOCzQ4cl2wOpnQ',
    appId: '1:531701629996:android:009a6f0d05c915e59d7d89',
    messagingSenderId: '531701629996',
    projectId: 'pentexe-3933d',
    storageBucket: 'pentexe-3933d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5TFGK8hX8vwJDhcqdfe0CkfMfnqkDmOQ',
    appId: '1:531701629996:ios:e8e3bbec0c2678249d7d89',
    messagingSenderId: '531701629996',
    projectId: 'pentexe-3933d',
    storageBucket: 'pentexe-3933d.appspot.com',
    iosClientId: '531701629996-440b1vb21i7i8n3cclp81kv8n31n9t2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.pentexe',
  );
}
